---
apiVersion: v1
kind: Namespace
metadata:
  name: phased-prow
  labels:
    name: phased
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: phased-prow
  namespace: phased-prow
  labels:
    tier: node
    name: phased
    app: phased
spec:
  selector:
    matchLabels:
      name: phased
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        name: phased
        app: phased
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: kube-phased-prow
        command: ["install-plugin"]
        args: ["/host/opt/cni/bin"]
        image: 'quay.io/oshoval/phased-prow:latest'
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
        volumeMounts:
        - name: cnibin
          mountPath: /host/opt/cni/bin
      volumes:
      - name: cnibin
        hostPath:
          path: /opt/cni/bin
          type: Directory
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: phased-prow
  namespace: default
spec:
  config: |
    {
      "cniVersion": "0.3.0",
      "type": "phased-prow"
    }
